# Site settings
title: Thaiane Braga
description: Um site sobre estudos, projetos, programação, engenharia de software, feminismo, vida, universo e tudo mais.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Thai Braga
user_title: Engenheira de Software
user_description: Sou apaixonada por programação e agilidade. Sempre tenho interesse em saber mais sobre arquitetura, qualidade, técnicas e tualmente meu tema de estudo preferido é segurança da informação e estou ficando paranóica com tanta informação interessante nesse mundo recém descoberto.
user_description_hobbies: Rubista, feminista e ativista. Penso que é dever de todos garantir uma sociedade mais justa para mulheres, negros, LGBTs e outras minorias de poder (que no fim, são muitas vezes a maioria em número nesse país).
email: thaianefbraga@gmail.com
github_username:  Thaiane

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
